import {DEVICE_CATALOG,LABS,PHASES} from './data.js';
import {state,rank,level,currentLabIndex,isUnlocked,phaseProgress,setActiveNav,updateTopStats} from './state.js';
import {isSignedIn,cloud} from './cloud.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],main=()=>$('#mainView');
let startLabHandler=()=>{};
export function setStartLabHandler(fn){startLabHandler=fn}
function deviceMiniSvg(type){
 const g='#17352b',k='#0b1712',led='#21aa69',y='#f2c94c';
 if(type==='pc')return `<svg viewBox="0 0 180 100"><rect x="36" y="14" width="95" height="59" rx="7" fill="${g}"/><rect x="43" y="21" width="81" height="45" rx="3" fill="#e9f8ef"/><rect x="77" y="73" width="16" height="9" fill="${g}"/><rect x="61" y="82" width="50" height="6" rx="3" fill="#527067"/></svg>`;
 if(type==='router')return `<svg viewBox="0 0 190 100"><rect x="20" y="30" width="150" height="42" rx="7" fill="${g}"/><circle cx="42" cy="51" r="4" fill="${led}"/><circle cx="55" cy="51" r="4" fill="${y}"/><rect x="92" y="44" width="19" height="16" rx="2" fill="${k}"/><rect x="117" y="44" width="19" height="16" rx="2" fill="${k}"/><path d="M60 31V19m50 12V19" stroke="${g}" stroke-width="5" stroke-linecap="round"/></svg>`;
 if(type==='firewall')return `<svg viewBox="0 0 190 100"><path d="M95 12l58 20v29c0 23-25 34-58 41-33-7-58-18-58-41V32l58-20Z" fill="#e8f7ee" stroke="${g}" stroke-width="6"/><path d="M69 52h52M95 31v43" stroke="${y}" stroke-width="7" stroke-linecap="round"/></svg>`;
 if(type==='server')return `<svg viewBox="0 0 190 100"><rect x="43" y="10" width="104" height="78" rx="8" fill="${g}"/>${[26,44,62].map(t=>`<rect x="55" y="${t}" width="80" height="11" rx="2" fill="${k}"/><circle cx="64" cy="${t+5}" r="2" fill="${led}"/>`).join('')}</svg>`;
 return `<svg viewBox="0 0 190 100"><rect x="18" y="28" width="154" height="45" rx="7" fill="${g}"/><text x="30" y="43" font-size="7" font-family="Arial" fill="#d9e8e1">ACCESS SWITCH</text>${Array.from({length:8},(_,i)=>`<rect x="${30+i*16}" y="50" width="11" height="10" rx="1" fill="${k}" stroke="#617a6e"/><circle cx="${33+i*16}" cy="47" r="1.5" fill="${i<2?led:'#62736b'}"/>`).join('')}</svg>`;
}
function moduleCard(l,i){return `<article class="module-card ${isUnlocked(i)?'':'locked'}" data-lab="${l.id}"><div class="module-icon">${deviceMiniSvg(l.devices.includes('switch')?'switch':l.devices[0])}</div><div class="module-top"><span class="difficulty">${l.difficulty}</span><span class="duration">◷ ${l.duration}</span></div><h3>${String(i+1).padStart(2,'0')} · ${l.title}</h3><p>${l.subtitle}</p><div class="module-outcome">You’ll be able to: ${l.outcome}</div><div class="module-cta"><b>${state.mastered.includes(l.id)?'★ Mastered':state.completed.includes(l.id)?'✓ Completed':'Start guided lab'}</b><span class="start-dot">→</span></div></article>`}
function bind(){
 $$('[data-action="signin"]').forEach(b=>b.onclick=()=>document.querySelector('[data-action="profile"]')?.click());
 $$('[data-action="continue"]').forEach(b=>b.onclick=()=>startLabHandler(state.currentLab));
 $$('[data-action="sandbox"]').forEach(b=>b.onclick=()=>startLabHandler('sandbox'));
 $$('[data-action="learn"]').forEach(b=>b.onclick=renderLearn);
 $$('[data-lab]').forEach(card=>card.onclick=()=>{const i=LABS.findIndex(l=>l.id===card.dataset.lab);if(!isUnlocked(i))return window.cyberToast?.('Complete the previous lab first.');startLabHandler(card.dataset.lab)});
}
export function renderHome(){setActiveNav('home');const m=main();m.className='page-shell';const idx=currentLabIndex(),next=LABS[idx],pathDone=state.completed.length;m.innerHTML=`
<section class="home-grid"><div class="welcome-card"><span class="kicker"><i class="kicker-dot"></i> Hands-on networking, from zero</span><h1>Build networks with your <span>own hands.</span></h1><p>Inspect real-looking devices, touch the ports, plug in cables, configure interfaces and watch packets move. CyberLab teaches the idea first—then lets you operate it.</p><div class="hero-actions"><button class="btn primary" data-action="continue">Continue learning →</button><button class="btn secondary" data-action="sandbox">🧪 Open free playground</button></div><div class="hero-lab-visual" aria-hidden="true"><div class="hero-desk"></div><div class="hero-screen"></div><div class="hero-switch"><div class="hero-port-row">${'<i></i>'.repeat(7)}</div></div><div class="hero-router"><div class="hero-port-row">${'<i></i>'.repeat(5)}</div></div><div class="hero-cable"></div></div></div><aside class="today-card"><div class="today-head"><h3>Today’s mission</h3><span>+150 XP</span></div><div class="mission-icon">${next.icon}</div><h4>${next.title}</h4><p>${next.outcome}</p><div class="progress-line"><i style="width:${Math.min(100,pathDone/LABS.length*100)}%"></i></div><div class="micro-copy"><span>Networking path</span><span>${pathDone}/${LABS.length-1} labs</span></div><button class="btn yellow" style="margin-top:auto" data-action="continue">Start mission</button></aside></section>
${isSignedIn()?'':`<div class="cloud-callout"><div><b>Keep your progress when you switch devices</b><br><span>Guest mode is free. Create an account only when you want cloud sync, streak history and account-backed mastery.</span></div><button class="btn soft" data-action="signin">Sign in</button></div>`}
<section class="metric-row"><div class="metric"><span class="metric-icon">🔥</span><div><strong>${state.streak}</strong><small>day streak</small></div></div><div class="metric"><span class="metric-icon">✦</span><div><strong>${state.xp}</strong><small>experience points</small></div></div><div class="metric"><span class="metric-icon">★</span><div><strong>${state.mastered.length}</strong><small>mastered labs</small></div></div><div class="metric"><span class="metric-icon">⌁</span><div><strong>${rank()[1]}</strong><small>current rank</small></div></div></section>
<div class="section-head"><div><h2>Your networking journey</h2><p>One concept at a time. You always know what comes next.</p></div><button class="link-btn" data-action="learn">View all labs →</button></div><section class="journey">${PHASES.slice(0,4).map((p,i)=>{const [d,t]=phaseProgress(p.id),locked=i>0&&phaseProgress(PHASES[i-1].id)[0]===0;return `<article class="phase-card ${i===0?'current':''} ${locked?'locked':''}"><span class="phase-num">${String(p.id).padStart(2,'0')}</span><h3>${p.title}</h3><p>${p.desc}</p><div class="phase-foot"><span>${p.range}</span><span>${d}/${t}</span></div></article>`}).join('')}</section>
<div class="section-head"><div><h2>Start with something tangible</h2><p>These first labs teach the physical network before configuration.</p></div></div><section class="library-grid">${LABS.slice(0,3).map((l,i)=>moduleCard(l,i)).join('')}</section>`;bind();updateTopStats()}
export function renderLearn(){setActiveNav('learn');const m=main();m.className='page-shell';m.innerHTML=`<div class="section-head" style="margin-top:0"><div><span class="kicker"><i class="kicker-dot"></i> Networking Foundations</span><h2 style="margin-top:14px">Learn the network from the cable upward</h2><p>Every module follows Learn → Inspect → Build → Configure → Prove → Practice.</p></div><button class="btn secondary" data-action="sandbox">🧪 Free playground</button></div><section class="library-grid">${LABS.slice(0,-1).map((l,i)=>moduleCard(l,i)).join('')}</section>`;bind()}
export function renderAchievements(){setActiveNav('achievements');const m=main(),cert=cloud.certificates?.[0],badges=[['🔌','First Link','Connect your first Ethernet cable',state.completed.includes('cabling-1')],['🌐','LAN Builder','Prove IPv4 connectivity',state.completed.includes('ipv4-1')],['★','Independent','Master a lab in Practice mode',state.mastered.length>0],['🧪','Experimenter','Open the free playground',false]];m.className='page-shell';m.innerHTML=`<div class="section-head" style="margin-top:0"><div><h2>Achievements</h2><p>Rewards represent things you actually did in the lab.</p></div></div>${isSignedIn()?`<div class="cloud-callout"><div><b>${cert?'Certificate record available':'Account-backed progress enabled'}</b><br><span>${cert?`Certificate ${cert.certificate_code} · ${cert.pathway}`:'Certificates stay locked until the full pathway is independently mastered and server-side grading is enabled.'}</span></div></div>`:'<div class="cloud-callout"><div><b>Achievements are local in Guest mode</b><br><span>Sign in to persist your learning history across devices.</span></div><button class="btn soft" data-action="signin">Sign in</button></div>'}<section class="library-grid">${badges.map(b=>`<article class="module-card ${b[3]?'':'locked'}"><div class="module-icon" style="font-size:52px">${b[0]}</div><h3>${b[1]}</h3><p>${b[2]}</p><div class="module-outcome">${b[3]?'Unlocked':'Locked'}</div></article>`).join('')}</section>`}
