export function createPanels(ctx){
 const $=s=>document.querySelector(s);
 function renderInspector(){
  const root=$('#inspectorRoot');if(!root)return;const d=ctx.selected();if(!d){root.innerHTML='';return}
  const cat=ctx.catalog[d.type],cfg=ctx.sim.getIp(d.id),tabs=['overview','ports','specs',...(d.type==='pc'||d.type==='server'?['network']:[])];
  root.innerHTML=`<aside class="inspector"><div class="inspect-head"><div><span class="panel-eyebrow">SELECTED DEVICE</span><h3>${cat.name}</h3><p>${d.name} · ${cat.layer}</p></div><button class="close-x" data-action="closeInspect" aria-label="Close inspector">✕</button></div><div class="inspect-tabs">${tabs.map(t=>`<button data-tab="${t}" class="${ctx.tab()===t?'active':''}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div><div class="inspect-body">${body(d,cat,cfg)}</div></aside>`;
  root.querySelector('[data-action="closeInspect"]').onclick=()=>ctx.closeInspect();
  root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{ctx.setTab(b.dataset.tab);renderInspector()});
  root.querySelectorAll('[data-inspect-port]').forEach(b=>b.onclick=()=>{ctx.record('inspectPort',`${d.id}:${b.dataset.inspectPort}`);ctx.toast(`${d.name} ${b.dataset.inspectPort}: ${b.dataset.portState==='up'?'link is up':'no cable connected'}.`);b.classList.add('seen')});
  root.querySelector('[data-action="saveIp"]')?.addEventListener('click',()=>{const ip=root.querySelector('#ipField').value.trim(),mask=root.querySelector('#maskField').value.trim();if(!/^\d{1,3}(\.\d{1,3}){3}$/.test(ip)||!/^\d{1,3}(\.\d{1,3}){3}$/.test(mask))return ctx.toast('Enter a valid IPv4 address and subnet mask.');ctx.sim.setIp(d.id,ip,mask);ctx.toast(`${d.name} network settings saved.`);ctx.record('configIp',d.type);renderInspector()})
 }
 function body(d,cat,cfg){
  if(ctx.tab()==='ports')return `<div class="def-card"><b>Physical interfaces</b><br>Click a port row to inspect it. The same port is also clickable on the device itself.</div><div class="port-table">${cat.ports.map(p=>{const up=!!ctx.sim.linkFor(d.id,p.id);return `<button class="port-row port-row-btn" data-inspect-port="${p.id}" data-port-state="${up?'up':'down'}"><span class="port-led ${up?'up':''}"></span><span><b>${p.label}</b><small>${p.type==='ethernet'?'RJ45 Ethernet':'Console'} · ${p.speed}</small></span><span class="port-state ${up?'up':''}">${up?'● Link up':'○ No link'}</span></button>`}).join('')}</div>`;
  if(ctx.tab()==='specs')return `<div class="spec-intro">These are the practical specifications a beginner should notice first.</div><div class="spec-grid">${Object.entries(cat.specs).map(([k,v])=>`<div class="spec"><small>${k}</small><b>${v}</b></div>`).join('')}</div>`;
  if(ctx.tab()==='network')return `<div class="def-card"><b>IPv4 settings</b><br>This gives the endpoint a Layer 3 identity. Byte tells you the exact values in Guided mode.</div><div class="network-form"><label><span>IPv4 address</span><input id="ipField" value="${cfg.ip==='Not configured'?'':cfg.ip}" placeholder="192.168.10.10"></label><label><span>Subnet mask</span><input id="maskField" value="${cfg.mask==='—'?'255.255.255.0':cfg.mask}" placeholder="255.255.255.0"></label><button class="btn primary" data-action="saveIp">Save network settings</button></div>`;
  return `<div class="device-profile"><div class="device-profile-icon">${cat.icon}</div><div><small>${cat.category}</small><h4>${cat.name}</h4><span>${cat.layer}</span></div></div><div class="def-card"><b>What does it do?</b><br>${cat.definition}</div><div class="insight-card"><span>Beginner focus</span><b>${d.type==='switch'?'Look at Ethernet ports and learn that a switch connects devices inside a LAN.':d.type==='router'?'Notice the smaller number of routed interfaces and its Layer 3 role.':d.type==='firewall'?'Notice Inside, Outside and DMZ — these are security zones.':'Find the Ethernet interface that connects this endpoint to the network.'}</b></div>`
 }
 function renderTerminal(){
  const box=$('#terminalDrawer');if(!box)return;const d=ctx.selected(),suggestions=d?(d.type==='pc'||d.type==='server'?['ipconfig','ping 192.168.10.20','help']:d.type==='switch'?['show interfaces status','show vlan brief','show running-config']:['show ip interface brief','show running-config','help']):[];
  box.className=`terminal-drawer ${ctx.terminalOpen()?'open':''}`;box.innerHTML=`<div class="terminal-top"><span class="term-dot"></span><span class="term-dot"></span><span class="term-dot"></span><b>${d?d.name:'Terminal'}</b><button data-action="closeTerminal">✕</button></div><div class="terminal-content"><div class="terminal-pane"><div class="terminal-output" id="terminalOutput">${d?`Connected to ${d.name}.\nClick a suggested command or type one below.\n`:'Select a device first.\n'}</div><div class="terminal-input-row"><span class="prompt">${d?d.name:'lab'}&gt;</span><input class="terminal-input" id="terminalInput" autocomplete="off" placeholder="Type a command…"><button class="term-run" data-run-command>Run</button></div></div><aside class="command-help"><h4>Try a command</h4>${suggestions.map(s=>`<button class="cmd-chip" data-cmd="${s}"><span>▶</span>${s}</button>`).join('')}<p class="command-explain">Clicking a command runs it immediately. The output tells you what the device currently knows.</p></aside></div>`;
  box.querySelector('[data-action="closeTerminal"]').onclick=()=>ctx.toggleTerminal(false);
  box.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>ctx.runCommand(b.dataset.cmd));
  const inp=$('#terminalInput'),run=()=>{if(inp?.value.trim()){ctx.runCommand(inp.value);inp.value=''}};if(inp)inp.onkeydown=e=>{if(e.key==='Enter')run()};box.querySelector('[data-run-command]')?.addEventListener('click',run)
 }
 return {renderInspector,renderTerminal};
}
